version: '3.8'

networks:
  two_apps:
    external: true

services:
  first-service:
    build: ./first
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://second-service:9080/first
    networks:
      - two_apps
    depends_on:
      second-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  second-service:
    build: ./second
    ports:
      - "9080:9080"
    networks:
      - two_apps
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
